/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ORACLE_U_H
#define EDGER8R_ORACLE_U_H

#include <openenclave/host.h>
#include "oracle_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_oracle_enclave(const char* path,
                                 oe_enclave_type_t type,
                                 uint32_t flags,
                                 const void* config,
                                 uint32_t config_size,
                                 oe_enclave_t** enclave);

/* List of ecalls */

oe_result_t get_remote_report_with_pubkey(
        oe_enclave_t* enclave,
        int* _retval,
        uint8_t** pem_key,
        size_t* key_size,
        uint8_t** remote_report,
        size_t* remote_report_size);
oe_result_t verify_report_and_set_pubkey(
        oe_enclave_t* enclave,
        int* _retval,
        uint8_t* pem_key,
        size_t key_size,
        uint8_t* remote_report,
        size_t remote_report_size);

OE_EXTERNC_END

#endif // EDGER8R_ORACLE_U_H
