/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_ORACLE_ARGS_H
#define EDGER8R_ORACLE_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */

/* #include <errno.h> - Errno propagation not enabled so not included. */

#include <openenclave/bits/result.h>

/**** User includes. ****/
/* There were no user includes. */

/**** User defined types in EDL. ****/
/* There were no user defined types. */

/**** ECALL marshalling structs. ****/
typedef struct _get_remote_report_with_pubkey_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t** pem_key;
    size_t* key_size;
    uint8_t** remote_report;
    size_t* remote_report_size;
} get_remote_report_with_pubkey_args_t;

typedef struct _verify_report_and_set_pubkey_args_t
{
    oe_result_t _result;
    int _retval;
    uint8_t* pem_key;
    size_t key_size;
    uint8_t* remote_report;
    size_t remote_report_size;
    uint8_t index;
} verify_report_and_set_pubkey_args_t;

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** Trusted function IDs ****/
enum
{
    oracle_fcn_id_get_remote_report_with_pubkey = 0,
    oracle_fcn_id_verify_report_and_set_pubkey = 1,
    oracle_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Untrusted function IDs. ****/
enum
{

    oracle_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

#endif // EDGER8R_ORACLE_ARGS_H
