/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "oracle_t.h"
#include <openenclave/edger8r/enclave.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN



/****** ECALL function wrappers  *************/
void ecall_get_remote_report_with_pubkey(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    get_remote_report_with_pubkey_args_t* pargs_in = (get_remote_report_with_pubkey_args_t*) input_buffer;
    get_remote_report_with_pubkey_args_t* pargs_out = (get_remote_report_with_pubkey_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_SET_OUT_POINTER(pem_key, sizeof(uint8_t*));
    OE_SET_OUT_POINTER(key_size, sizeof(size_t));
    OE_SET_OUT_POINTER(remote_report, sizeof(uint8_t*));
    OE_SET_OUT_POINTER(remote_report_size, sizeof(size_t));

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = get_remote_report_with_pubkey(
        pargs_in->pem_key,
        pargs_in->key_size,
        pargs_in->remote_report,
        pargs_in->remote_report_size);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ecall_verify_report_and_set_pubkey(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    verify_report_and_set_pubkey_args_t* pargs_in = (verify_report_and_set_pubkey_args_t*) input_buffer;
    verify_report_and_set_pubkey_args_t* pargs_out = (verify_report_and_set_pubkey_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(pem_key, (pargs_in->key_size * sizeof(uint8_t)));
    OE_SET_IN_POINTER(remote_report, (pargs_in->remote_report_size * sizeof(uint8_t)));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Check that in/in-out strings are null terminated */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    pargs_out->_retval = verify_report_and_set_pubkey(
        pargs_in->pem_key,
        pargs_in->key_size,
        pargs_in->remote_report,
        pargs_in->remote_report_size);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}



/****** ECALL function table  *************/
oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_get_remote_report_with_pubkey,
    (oe_ecall_func_t) ecall_verify_report_and_set_pubkey,
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

OE_EXTERNC_END
