/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef ORACLE_ARGS_H
#define ORACLE_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

typedef struct _get_remote_report_with_pubkey_args_t {
    oe_result_t _result;
	int _retval;
	uint8_t** pem_key;
	size_t* key_size;
	uint8_t** remote_report;
	size_t* remote_report_size;
 } get_remote_report_with_pubkey_args_t;

typedef struct _verify_report_and_set_pubkey_args_t {
    oe_result_t _result;
	int _retval;
	uint8_t* pem_key;
	size_t key_size;
	uint8_t* remote_report;
	size_t remote_report_size;
 } verify_report_and_set_pubkey_args_t;

/* trusted function ids */
enum {
    fcn_id_get_remote_report_with_pubkey = 0,
    fcn_id_verify_report_and_set_pubkey = 1,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // ORACLE_ARGS_H
